blank_issues_enabled: false
contact_links:
  - name: DAVx‚Åµ Community Support
    url: https://github.com/bitfireAT/davx5-ose/discussions
    about: Ask and answer questions (including feature requests and bug reports) here.
