name: Update Weblate Credits

on:
  pull_request:
    # Trigger when a PR is opened, or when Weblate pushes new commits to it
    types: [ opened, synchronize ]

jobs:
  update-credits:
    runs-on: ubuntu-latest

    # Run only if the PR creator is 'weblate'
    if: github.actor == 'weblate'

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        # Checkout the head ref of the PR
        ref: ${{ github.head_ref }}
        # Fetch full history to ensure git operations work smoothly
        fetch-depth: 0
    - name: Fetch Weblate credits
      run: ./scripts/fetch-weblate-translators.sh
      env:
        WEBLATE_API_TOKEN: ${{ secrets.WEBLATE_API_TOKEN }}
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "Update credits"
        file_pattern: weblate-translators.json
