name: Update Weblate translators

on:
  pull_request:
    # Trigger when a PR is opened, or when Weblate pushes new commits to it
    types: [ opened, synchronize ]

jobs:
  update-translators:
    runs-on: ubuntu-latest

    # Run only if the PR creator is 'weblate' (or in the PR that added the workflow, for testing)
    if: github.actor == 'weblate' || github.ref == 'refs/pull/1918/merge'

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        # Checkout the head ref of the PR
        ref: ${{ github.head_ref }}

    - name: Fetch Weblate translators
      run: ./scripts/fetch-weblate-translators.sh
      env:
        WEBLATE_API_TOKEN: ${{ secrets.WEBLATE_API_TOKEN }}

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "Update translators"
        file_pattern: weblate-translators.json
