name: Update Weblate Credits

# Run whenever a PR made by the user "weblate" is merged into the main branch
on:
  push:
    branches:
      - main-ose
    authors:
      - weblate

jobs:
  update-credits:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: main-ose
    - name: Fetch Weblate credits
      run: ./scripts/fetch-weblate-credits.sh
      env:
        WEBLATE_API_TOKEN: ${{ secrets.WEBLATE_API_TOKEN }}
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v7
      branch: main-ose
      with:
        commit_message: "Update Weblate credits"
        file_pattern: credits.json
